# Database
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate #drops tables every tine it runs create-drop
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# App
spring.application.name=taskflow
server.port=${PORT:8080}

#thymeleaf
spring.thymeleaf.cache=false
spring.thymeleaf.enabled=true
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html