# Database
spring.datasource.url=jdbc:mysql://localhost:3306/taskflow_db
spring.datasource.username=root
spring.datasource.password=Digvijay@1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate #drops tables every tine it runs create-drop
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# App
spring.application.name=taskflow
server.port=8080

#thymeleaf
spring.thymeleaf.cache=false
spring.thymeleaf.enabled=true
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html